# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Shushao_config = debug
  Game_config = debug

else ifeq ($(config),release)
  Shushao_config = release
  Game_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Shushao Game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Shushao:
ifneq (,$(Shushao_config))
	@echo "==== Building Shushao ($(Shushao_config)) ===="
	@${MAKE} --no-print-directory -C Shushao -f Makefile config=$(Shushao_config)
endif

Game: Shushao
ifneq (,$(Game_config))
	@echo "==== Building Game ($(Game_config)) ===="
	@${MAKE} --no-print-directory -C Game -f Makefile config=$(Game_config)
endif

clean:
	@${MAKE} --no-print-directory -C Shushao -f Makefile clean
	@${MAKE} --no-print-directory -C Game -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Shushao"
	@echo "   Game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"