#pragma once

/* include in derived projects */

// ShushaoEngine Objects
#include "design.h"
#include "constants.h"
#include "types.h"
#include "camera.h"
#include "color.h"
#include "component.h"
#include "program.h"
#include "config.h"
#include "cycle.h"
#include "debug.h"
#include "logger.h"
#include "entity.h"
#include "glmanager.h"
#include "linerenderer.h"
#include "maincamera.h"
#include "material.h"
#include "input.h"
#include "object.h"
#include "rect.h"
#include "renderer.h"
#include "resources.h"
#include "scene.h"
#include "scenemanager.h"
#include "service.h"
#include "setime.h"
#include "shaders/shader.h"
#include "sprite.h"
#include "spriterenderer.h"
#include "system.h"
#include "texture.h"
#include "textureatlas.h"
#include "transform.h"
#include "utility.h"
#include "spritesheet.h"
#include "timeline.h"
#include "animation.h"
#include "audio.h"
#include "physics.h"
#include "rigidbody2d.h"
#include "collider2d.h"
#include "collision2d.h"
#include "font.h"
#include "text.h"
#include "meshrenderer.h"
#include "shaders/phongshader.h"
#include "canvas.h"

// UI
#include "ui/canvas.h"
#include "ui/text.h"

