#pragma once

#include "Shushao/Application.h"

// ---Entry Point---------------------
#include "Shushao/Start.h"
// -----------------------------------

#include "Shushao/Debug.h"
#include "Shushao/Resources.h"
#include "Shushao/Resources/resources.h"  // rc
#include "Shushao/Animation.h"
#include "Shushao/Audio.h"
#include "Shushao/Camera.h"
#include "Shushao/Canvas.h"
#include "Shushao/Color.h"
#include "Shushao/Component.h"
#include "Shushao/Config.h"
#include "Shushao/Coroutine.h"
#include "Shushao/Design.h"
#include "Shushao/Entity.h"
#include "Shushao/MainCamera.h"
#include "Shushao/Factory.h"
#include "Shushao/Font.h"
#include "Shushao/GeometryRenderer.h"
#include "Shushao/GLManager.h"
#include "Shushao/Gradient.h"
#include "Shushao/Image.h"
#include "Shushao/Input.h"
#include "Shushao/Logger.h"
#include "Shushao/Material.h"
#include "Shushao/MeshRenderer.h"
#include "Shushao/Object.h"
#include "Shushao/Program.h"
#include "Shushao/RawImage.h"
#include "Shushao/Rect.h"
#include "Shushao/Renderer.h"
#include "Shushao/Resource.h"
#include "Shushao/Scene.h"
#include "Shushao/SceneManager.h"
#include "Shushao/Service.h"
#include "Shushao/Sprite.h"
#include "Shushao/SpriteRenderer.h"
#include "Shushao/SpriteSheet.h"
#include "Shushao/Time.h"
#include "Shushao/System.h"
#include "Shushao/Text.h"
#include "Shushao/Textfile.h"
#include "Shushao/Texture.h"
#include "Shushao/TextureAtlas.h"
#include "Shushao/Timeline.h"
#include "Shushao/Transform.h"
#include "Shushao/Utility.h"
#include "Shushao/Variation.h"

// PHYSICS
#include "Shushao/Physics/Collider2d.h"
#include "Shushao/Physics/Collision2d.h"
#include "Shushao/Physics/Physics.h"
#include "Shushao/Physics/Rigidbody2d.h"

// PARTICLE SYSTEM
#include "Shushao/ParticleSystem.h"

// UI
#include "Shushao/UI/CanvasUI.h"
#include "Shushao/UI/ImageUI.h"
#include "Shushao/UI/PanelUI.h"
#include "Shushao/UI/RawImageUI.h"
#include "Shushao/UI/TextUI.h"