#pragma once

/* include in derived projects */

// ShushaoEngine Objects
#include "camera.h"
#include "color.h"
#include "component.h"
#include "program.h"
#include "config.h"
#include "cycle.h"
#include "debug.h"
#include "debuggrid.h"
#include "entity.h"
#include "gamedata.h"
#include "glmanager.h"
#include "inputmanager.h"
#include "linerenderer.h"
#include "macros.h"
#include "maincamera.h"
#include "material.h"
#include "model.h"
#include "object.h"
#include "rect.h"
#include "renderer.h"
#include "resources.h"
#include "scene.h"
#include "scenemanager.h"
#include "service.h"
#include "setime.h"
#include "shader.h"
#include "sprite.h"
#include "spriterenderer.h"
#include "system.h"
#include "texture.h"
#include "textureatlas.h"
#include "transform.h"
#include "utility.h"
#include "spritesheet.h"
#include "timeline.h"
#include "animation.h"
